language: java
jdk:
  - openjdk11

branches:
  only:
    - master #master branch에 push될 때만 ci

#TRAVIS-CI 서버의 HOME
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

#CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - albatross1886@gmail.com
      - mkkw2047@gmail.com