#codedeploy 환경설정
version: 0.0
os: linux
files:
  - source:  /
    destination: /home/ec2-user/service/s3/zip
    overwrite: yes
hooks:
  AfterInstall:
    - location: execute-deploy.sh
      timeout: 180
