server:
  #address: 172.31.34.11
  #port: 80
  port: 8000
  #port: 443 #https

spring:
  profiles:
    active: real
    #active: local
    #include: oauth
  config:
    imports: classpath:/s3.yml

  jpa:
    properties:
      hibernate:
        format-sql: true
        show-sql: true
  thymeleaf:
    cache: false
  session:
    store-type: jdbc
devtools:
  livereload:
    enabled: true
