server:
  #address: 172.31.34.11
  port: 8000

spring:
  profiles:
    active: real
    #active: local
    #include: oauth
  jpa:
    properties:
      hibernate:
        format-sql: true
        show-sql: true
  thymeleaf:
    cache: false
  session:
    store-type: jdbc
devtools:
  livereload:
    enabled: true
