server:
  port: 8000
  tomcat:
    uri-encoding: UTF-8

spring:
  profiles:
    active: real
    #active: local
    #include: oauth
  jpa:
    properties:
      hibernate:
        format-sql: true
        show-sql: true
  thymeleaf:
    cache: false
devtools:
  livereload:
    enabled: true
