#운영 db
spring:
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:mariadb://albatross-backend.c0ugomampxf1.ap-northeast-2.rds.amazonaws.com:3306/albatross
      driver-class-name: org.mariadb.jdbc.Driver
      username: albatross
      password: albatross1886